package com.component;

import com.model.User;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Cristian
 * Clase componente que dibuja el logo y muestra los datos
 * del usuario logeado
 */
public class Header extends javax.swing.JPanel {

    /**
     * Atributos que facilitan el renderizado del componente
     * 
     * xArc: ejeX del punto de inicio del dibujo del arco del header
     * yArc: ejeY del punto de inicio del dibujo del arco del header
     * widthArc: anchura de la arco (solo se muestra la mitad)
     * heightArc: altura de la arco (solo se muestra la mitad)
     * arcAngle: angulo de inicio que terminara el dibujado del arco
     */
    
    public int xArc, yArc, widthArc, heightArc = 60, arcAngle = 90;
    
    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();
    }
    
    //* Cambiar la informacion del usuario logeado en la cabecera
    public void setUserInfo(User user) {
        username.setText(user.getUsername());
        position.setText(user.getPosition());
    }
    
    @Override //* Dibuja|Renderiza el componente
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        // Antialiasing para mejor calidad
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Dibujar líneas blancas decorativas
        g2d.setColor(Color.WHITE);
        g2d.setStroke(new BasicStroke(2));
        
        g2d.drawLine(130, 30, 147, 48);
        g2d.drawLine(130, 40, 150, 60);
        
        g2d.drawLine(147, 48, 163, 0);
        g2d.drawLine(150, 60, 166, 13);
        
        g2d.drawLine(169, 0, 184, 48);
        g2d.drawLine(166, 13, 180, 60);
        
        g2d.drawLine(184, 48, 201, 34);
        g2d.drawLine(180, 60, 200, 41);
        
        g2d.drawLine(202, 34, 250, 34);
        g2d.drawLine(201, 40, 255, 40);
        
        g2d.drawArc(250, 20, 60, 30, 180, -180);
        g2d.drawArc(255, 25, 50, 30, 180, -180);
        
        g2d.drawLine(310, 34, getWidth()-30, 34);
        g2d.drawLine(305, 40, getWidth()-30, 40);
        
        g2d.drawLine(getWidth()-30, 34, getWidth()-30, 40);
        // Dibujar una curva del footer
        widthArc = getWidth();
        xArc = -widthArc/2;
        yArc = getHeight() - heightArc/2;
        
        g2d.fillArc(xArc, yArc, widthArc, heightArc, 0, arcAngle);
//        g2d.fillArc(widthArc/2, -heightArc/2, widthArc, 40, -arcAngle, -arcAngle);
        
        g2d.drawArc(xArc, yArc - 10 , widthArc + 8, heightArc, 0, arcAngle);
        
        g2d.drawArc(-xArc + 9, yArc + 18, 20, 6, 180, 90);
        
        int x = -xArc + 9 + 10, y = yArc + 24; 
        
        g2d.drawLine(x, y, getWidth(), y);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        panelUserInfo = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        avatar = new javax.swing.JLabel();
        position = new javax.swing.JLabel();

        setBackground(new java.awt.Color(41, 117, 185));
        setPreferredSize(new java.awt.Dimension(875, 100));

        logo.setBackground(new java.awt.Color(240, 240, 240));
        logo.setFont(new java.awt.Font("Impact", 3, 40)); // NOI18N
        logo.setForeground(new java.awt.Color(51, 143, 214));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setText("TBP");
        logo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(240, 240, 240)), javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(41, 117, 185))));
        logo.setOpaque(true);
        logo.setPreferredSize(new java.awt.Dimension(100, 72));

        panelUserInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelUserInfo.setOpaque(false);

        username.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(194, 198, 218));
        username.setText("{Username}");
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-avatar.png"))); // NOI18N
        avatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        position.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        position.setForeground(new java.awt.Color(194, 198, 218));
        position.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        position.setText("{position}");
        position.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelUserInfoLayout = new javax.swing.GroupLayout(panelUserInfo);
        panelUserInfo.setLayout(panelUserInfoLayout);
        panelUserInfoLayout.setHorizontalGroup(
            panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(position)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avatar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUserInfoLayout.setVerticalGroup(
            panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserInfoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(avatar))
                .addGap(0, 0, 0)
                .addComponent(position)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                .addComponent(panelUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelUserInfo;
    private javax.swing.JLabel position;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
