package com.component;

/**
 *
 * @author Cristian
 */
public class InvoiceItem extends javax.swing.JPanel {

    /**
     * Creates new form InvoiceItem
     */
    public InvoiceItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerInvoice = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        fullNameClient = new javax.swing.JLabel();
        btnLoad = new com.component.complement.ActionButton(10);
        footerInvoice = new javax.swing.JPanel();
        subTotal = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(540, 100));

        headerInvoice.setBackground(new java.awt.Color(41, 117, 185));
        headerInvoice.setPreferredSize(new java.awt.Dimension(540, 50));

        date.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        date.setForeground(new java.awt.Color(250, 250, 250));
        date.setText("Fecha: 01/01/2001");

        fullNameClient.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fullNameClient.setForeground(new java.awt.Color(250, 250, 250));
        fullNameClient.setText("Nombre: {fullNameClient}");

        btnLoad.setBackground(new java.awt.Color(45, 112, 172));
        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.png"))); // NOI18N
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerInvoiceLayout = new javax.swing.GroupLayout(headerInvoice);
        headerInvoice.setLayout(headerInvoiceLayout);
        headerInvoiceLayout.setHorizontalGroup(
            headerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerInvoiceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(date)
                .addGap(18, 18, 18)
                .addComponent(fullNameClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnLoad)
                .addContainerGap())
        );
        headerInvoiceLayout.setVerticalGroup(
            headerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerInvoiceLayout.createSequentialGroup()
                .addGroup(headerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerInvoiceLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(headerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date)
                            .addComponent(fullNameClient)))
                    .addGroup(headerInvoiceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLoad)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        footerInvoice.setBackground(new java.awt.Color(41, 117, 185));
        footerInvoice.setPreferredSize(new java.awt.Dimension(540, 50));

        subTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        subTotal.setForeground(new java.awt.Color(250, 250, 250));
        subTotal.setText("subTotal: {{subTotal}}");

        total.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        total.setForeground(new java.awt.Color(250, 250, 250));
        total.setText("Total: {{total}}");

        javax.swing.GroupLayout footerInvoiceLayout = new javax.swing.GroupLayout(footerInvoice);
        footerInvoice.setLayout(footerInvoiceLayout);
        footerInvoiceLayout.setHorizontalGroup(
            footerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerInvoiceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(subTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total)
                .addGap(20, 20, 20))
        );
        footerInvoiceLayout.setVerticalGroup(
            footerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerInvoiceLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(footerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotal)
                    .addComponent(total))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(footerInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        
    }//GEN-LAST:event_btnLoadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JLabel date;
    private javax.swing.JPanel footerInvoice;
    private javax.swing.JLabel fullNameClient;
    private javax.swing.JPanel headerInvoice;
    private javax.swing.JLabel subTotal;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
