package com.component;

import java.awt.Color;

/**
 *
 * @author Cristian
 */
public class MenuBar extends javax.swing.JPanel {

    public Color normal = new Color(51,143,214), hover = new Color(41,113,184);
    
    /**
     * Creates new form MenuBar
     */
    public MenuBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnRegisterSale = new javax.swing.JButton();
        btnTrackRecord = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(41, 117, 185));
        setMinimumSize(new java.awt.Dimension(405, 680));

        title.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Menu");
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        btnHome.setBackground(new java.awt.Color(51, 143, 214));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_logo.png"))); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setIconTextGap(15);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnRegisterSale.setBackground(new java.awt.Color(51, 143, 214));
        btnRegisterSale.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegisterSale.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cart-shopping.png"))); // NOI18N
        btnRegisterSale.setText("Registrar Venta");
        btnRegisterSale.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnRegisterSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterSale.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegisterSale.setIconTextGap(15);
        btnRegisterSale.setPreferredSize(new java.awt.Dimension(75, 34));
        btnRegisterSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterSaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterSaleMouseExited(evt);
            }
        });
        btnRegisterSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterSaleActionPerformed(evt);
            }
        });

        btnTrackRecord.setBackground(new java.awt.Color(51, 143, 214));
        btnTrackRecord.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTrackRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnTrackRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/track-record.png"))); // NOI18N
        btnTrackRecord.setText("Historial de Ventas");
        btnTrackRecord.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnTrackRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrackRecord.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrackRecord.setIconTextGap(15);
        btnTrackRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrackRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrackRecordMouseExited(evt);
            }
        });
        btnTrackRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackRecordActionPerformed(evt);
            }
        });

        btnInventory.setBackground(new java.awt.Color(51, 143, 214));
        btnInventory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory.png"))); // NOI18N
        btnInventory.setText("Inventario");
        btnInventory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventory.setIconTextGap(15);
        btnInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventoryMouseExited(evt);
            }
        });
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });

        btnUsers.setBackground(new java.awt.Color(51, 143, 214));
        btnUsers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/users.png"))); // NOI18N
        btnUsers.setText("Usuarios");
        btnUsers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsers.setIconTextGap(15);
        btnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsersMouseExited(evt);
            }
        });
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(51, 143, 214));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_logo.png"))); // NOI18N
        btnLogOut.setText("Cerrar Sesión");
        btnLogOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogOut.setIconTextGap(15);
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addComponent(btnTrackRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addComponent(btnRegisterSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(title)
                .addGap(50, 50, 50)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRegisterSale, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTrackRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterSaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterSaleMouseEntered
        btnRegisterSale.setBackground(hover);
        btnRegisterSale.revalidate();
        btnRegisterSale.repaint();
    }//GEN-LAST:event_btnRegisterSaleMouseEntered

    private void btnRegisterSaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterSaleMouseExited
        btnRegisterSale.setBackground(normal);
        btnRegisterSale.revalidate();
        btnRegisterSale.repaint();
    }//GEN-LAST:event_btnRegisterSaleMouseExited

    private void btnRegisterSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSaleActionPerformed
        
    }//GEN-LAST:event_btnRegisterSaleActionPerformed

    private void btnTrackRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackRecordMouseEntered
        btnTrackRecord.setBackground(hover);
        btnTrackRecord.revalidate();
        btnTrackRecord.repaint();
    }//GEN-LAST:event_btnTrackRecordMouseEntered

    private void btnTrackRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackRecordMouseExited
        btnTrackRecord.setBackground(normal);
        btnTrackRecord.revalidate();
        btnTrackRecord.repaint();
    }//GEN-LAST:event_btnTrackRecordMouseExited

    private void btnTrackRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackRecordActionPerformed
        
    }//GEN-LAST:event_btnTrackRecordActionPerformed

    private void btnInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseEntered
        btnInventory.setBackground(hover);
        btnInventory.revalidate();
        btnInventory.repaint();
    }//GEN-LAST:event_btnInventoryMouseEntered

    private void btnInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseExited
        btnInventory.setBackground(normal);
        btnInventory.revalidate();
        btnInventory.repaint();
    }//GEN-LAST:event_btnInventoryMouseExited

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        btnLogOut.setBackground(hover);
        btnLogOut.revalidate();
        btnLogOut.repaint();
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        btnLogOut.setBackground(normal);
        btnLogOut.revalidate();
        btnLogOut.repaint();
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseEntered
        btnUsers.setBackground(hover);
        btnUsers.revalidate();
        btnUsers.repaint();
    }//GEN-LAST:event_btnUsersMouseEntered

    private void btnUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseExited
        btnUsers.setBackground(normal);
        btnUsers.revalidate();
        btnUsers.repaint();
    }//GEN-LAST:event_btnUsersMouseExited

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setBackground(normal);
        btnHome.revalidate();
        btnHome.repaint();
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setBackground(hover);
        btnHome.revalidate();
        btnHome.repaint();
    }//GEN-LAST:event_btnHomeMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRegisterSale;
    private javax.swing.JButton btnTrackRecord;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
