package com.component;

import com.event.FormUserEvent;
import com.model.User;
import com.model.UserInfo;
import com.util.ValidateInput;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 * Clase de componente visual que se encarga de mostrar
 * los inputs del formulario ya sea para crear, editar o buscar
 */
public class PanelFormUser extends javax.swing.JPanel {
    
    /**
     * Atributos que mejoran e facilitan la impletmentacion de la logica de la clase
     * 
     * mode: constante que ayuda en la reutilizacion del componente para realizar distintos procesos
     * user: objeto que contiene los datos user que fue seleccionado para editar
     * userInfo: objeto que almacena la info personal del usuario seleccionado
     * show: dato que valida si mostrar el texto del inputPassword, cuando iconShowAndHidden es presionado
     * userEvent: variable que contiene funciones que se ejecutan cuando ocurren ciertos eventos y dependiendo el mode
     */
    
    private final int mode; // 0: buscar. 1: crear. 2: editar
    private User user;
    private UserInfo userInfo;
    private boolean show = false;
    private FormUserEvent userEvent;
    
    /**
     * Creates new form PanelFormUser
     */
    public PanelFormUser(FormUserEvent userEvent, int mode) {
        initComponents();
        this.userEvent = userEvent;
        this.mode = mode;
        
        if(mode == 0) { 
            title.setText("Buscar");
            btn.setText("Buscar");
            
            labelPassword.setVisible(false);
            separatorPassword.setVisible(false);
            inputPassword.setVisible(false);
            iconShowAndHidden.setVisible(false);
            
            selectRole.insertItemAt("Cualquiera", 0);
            selectRole.setSelectedIndex(0);
        } else if(mode == 1) {
            title.setText("Registrar");
            btn.setText("Registrar");
        } else {
            title.setText("Editar");
            btn.setText("Editar");
        }
    }
    
    //* Instancia|Cambia el valor del usuario que va ser editado
    public void setUser(User user, UserInfo userInfo) {
        this.user = user;
        this.userInfo = userInfo;
        setValues();
    }
    
    //* Se inserta los valores del usuario que va ser editado en los inputs
    private void setValues() {
        inputUsername.setText(user.getUsername());
        inputFirstName.setText(userInfo.getFirstName());
        inputLastName.setText(userInfo.getLastName());
        inputCI.setText(userInfo.getCi());
        inputPhone.setText(userInfo.getPhone());
        inputPassword.setText(user.getPassword());
        selectRole.setSelectedIndex(user.getPosition().contains("employee") ? 0 : 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new com.component.complement.ScrollPaneWin11();
        form = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        separatorUsername = new javax.swing.JSeparator();
        inputUsername = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        separatorFirstName = new javax.swing.JSeparator();
        inputFirstName = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        separatorLastName = new javax.swing.JSeparator();
        inputLastName = new javax.swing.JTextField();
        labelCI = new javax.swing.JLabel();
        separatorCI = new javax.swing.JSeparator();
        inputCI = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        separatorPhone = new javax.swing.JSeparator();
        inputPhone = new javax.swing.JTextField();
        labelRole = new javax.swing.JLabel();
        separatorRole = new javax.swing.JSeparator();
        selectRole = new com.component.complement.ComboBox<>();
        labelPassword = new javax.swing.JLabel();
        separatorPassword = new javax.swing.JSeparator();
        inputPassword = new javax.swing.JPasswordField();
        iconShowAndHidden = new javax.swing.JLabel();
        btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 210, 210));

        scroll.setBorder(null);

        form.setBackground(new java.awt.Color(210, 210, 210));
        form.setPreferredSize(new java.awt.Dimension(320, 685));

        title.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        title.setForeground(new java.awt.Color(60, 60, 60));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Registrar");

        labelUsername.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(60, 60, 60));
        labelUsername.setText("Usuario:");

        separatorUsername.setForeground(new java.awt.Color(41, 117, 185));

        inputUsername.setBackground(new java.awt.Color(180, 180, 180));
        inputUsername.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(55, 55, 55));
        inputUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputUsername.setName("Usuario"); // NOI18N

        labelFirstName.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelFirstName.setForeground(new java.awt.Color(60, 60, 60));
        labelFirstName.setText("Nombre:");

        separatorFirstName.setForeground(new java.awt.Color(41, 117, 185));

        inputFirstName.setBackground(new java.awt.Color(180, 180, 180));
        inputFirstName.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputFirstName.setForeground(new java.awt.Color(55, 55, 55));
        inputFirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputFirstName.setName("Nombre"); // NOI18N

        labelLastName.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelLastName.setForeground(new java.awt.Color(60, 60, 60));
        labelLastName.setText("Apellido:");

        separatorLastName.setForeground(new java.awt.Color(41, 117, 185));

        inputLastName.setBackground(new java.awt.Color(180, 180, 180));
        inputLastName.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputLastName.setForeground(new java.awt.Color(55, 55, 55));
        inputLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputLastName.setName("Apellido"); // NOI18N

        labelCI.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelCI.setForeground(new java.awt.Color(60, 60, 60));
        labelCI.setText("Cedula:");

        separatorCI.setForeground(new java.awt.Color(41, 117, 185));

        inputCI.setBackground(new java.awt.Color(180, 180, 180));
        inputCI.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputCI.setForeground(new java.awt.Color(55, 55, 55));
        inputCI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputCI.setName("Cedula"); // NOI18N

        labelPhone.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelPhone.setForeground(new java.awt.Color(60, 60, 60));
        labelPhone.setText("Telefono:");

        separatorPhone.setForeground(new java.awt.Color(41, 117, 185));

        inputPhone.setBackground(new java.awt.Color(180, 180, 180));
        inputPhone.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputPhone.setForeground(new java.awt.Color(55, 55, 55));
        inputPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputPhone.setName("Telefono"); // NOI18N

        labelRole.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelRole.setForeground(new java.awt.Color(60, 60, 60));
        labelRole.setText("Rol:");

        separatorRole.setForeground(new java.awt.Color(41, 117, 185));

        selectRole.setBackground(new java.awt.Color(180, 180, 180));
        selectRole.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        selectRole.setForeground(new java.awt.Color(55, 55, 55));
        selectRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Supervisor", "Admin" }));
        selectRole.setBorder(null);
        selectRole.setPreferredSize(new java.awt.Dimension(97, 27));

        labelPassword.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(60, 60, 60));
        labelPassword.setText("Contraseña:");

        separatorPassword.setForeground(new java.awt.Color(41, 117, 185));

        inputPassword.setBackground(new java.awt.Color(180, 180, 180));
        inputPassword.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputPassword.setName("Contraseña"); // NOI18N

        iconShowAndHidden.setBackground(new java.awt.Color(180, 180, 180));
        iconShowAndHidden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconShowAndHidden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        iconShowAndHidden.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        iconShowAndHidden.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iconShowAndHidden.setOpaque(true);
        iconShowAndHidden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconShowAndHiddenMouseClicked(evt);
            }
        });

        btn.setBackground(new java.awt.Color(45, 155, 240));
        btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn.setForeground(new java.awt.Color(250, 250, 250));
        btn.setText("Registrar");
        btn.setBorder(null);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn.setPreferredSize(new java.awt.Dimension(92, 30));
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(formLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(inputPassword)
                        .addGap(0, 0, 0)
                        .addComponent(iconShowAndHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(labelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(190, 190, 190))
                    .addComponent(inputUsername)
                    .addComponent(separatorUsername)
                    .addComponent(separatorFirstName)
                    .addComponent(inputFirstName)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(labelLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorLastName)
                    .addComponent(inputLastName)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(labelCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorCI)
                    .addComponent(inputCI)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(labelPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorPhone)
                    .addComponent(inputPhone)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorPassword)
                    .addComponent(selectRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(labelRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorRole))
                .addGap(25, 25, 25))
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorCI, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCI, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorRole, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(selectRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconShowAndHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        scroll.setViewportView(form);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
    }// </editor-fold>//GEN-END:initComponents

    //* Cambia la legibilidad del texto que se encuentra en el inputPassword presionando el iconShowAndHidden
    private void iconShowAndHiddenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconShowAndHiddenMouseClicked
        show = !show;
        if(show) {
            inputPassword.setEchoChar((char) 0);
            iconShowAndHidden.setIcon(new ImageIcon(getClass().getResource("/closed-eye.png")));
        } else {
            inputPassword.setEchoChar('•');
            iconShowAndHidden.setIcon(new ImageIcon(getClass().getResource("/eye.png")));
        }
    }//GEN-LAST:event_iconShowAndHiddenMouseClicked

    //* Extrae el texto de los inputs y dependiento del mode los valida para realizar sus respectivos procesos; buscar, crear o editar
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        try {
            
            String username = inputUsername.getText(), firstName = inputFirstName.getText(), lastName = inputLastName.getText(),
                    ci = inputCI.getText(), phone = inputPhone.getText(), password = new String(inputPassword.getPassword()), 
                    rol = selectRole.getSelectedItem().toString();
            
            String position = (rol.contains("Admin")) ? "admin" : (rol.contains("Empleado")) ? "employee" : (rol.contains("Supervisor")) ? "manager" :rol;
            
            if(mode == 0) {
                userEvent.onSearch(username, firstName, lastName, ci, phone, position);
                
            } else {
                ValidateInput.isEmptyOrBlank(List.of(inputUsername, inputFirstName, inputLastName, inputCI, inputPhone, inputPassword));
                
                ValidateInput.isMinimumLength(inputPassword, 8);
                
                if(mode == 1) {
                    userEvent.onCreate(username, password, firstName, lastName, ci, phone, position);
                    
                    inputUsername.setText("");
                    inputFirstName.setText("");
                    inputLastName.setText("");
                    inputCI.setText("");
                    inputPhone.setText("");
                    inputPassword.setText("");
                    
                } else {
                    int option = JOptionPane.showConfirmDialog(null,"¿Esta seguro de editar este usuario?", "Advertencia",
                                                                JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
                    
                    user.setUsername(username);
                    user.setPassword(password);
                    user.setPosition(position);
                    
                    userInfo.setFirstName(firstName);
                    userInfo.setLastName(lastName);
                    userInfo.setPhone(phone);
                    userInfo.setCi(ci);
                    
                    if(option == 0)
                        userEvent.onEdit(user, userInfo);
                }
            } 

        } catch(Exception e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"No se puede avanzar debido a que: \n" + e.getMessage(),"Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JPanel form;
    private javax.swing.JLabel iconShowAndHidden;
    private javax.swing.JTextField inputCI;
    private javax.swing.JTextField inputFirstName;
    private javax.swing.JTextField inputLastName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel labelCI;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JComboBox<String> selectRole;
    private javax.swing.JSeparator separatorCI;
    private javax.swing.JSeparator separatorFirstName;
    private javax.swing.JSeparator separatorLastName;
    private javax.swing.JSeparator separatorPassword;
    private javax.swing.JSeparator separatorPhone;
    private javax.swing.JSeparator separatorRole;
    private javax.swing.JSeparator separatorUsername;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
