package com.component;

import java.awt.event.ActionListener;

/**
 *
 * @author Cristian
 */
public class PanelFormSignUp extends javax.swing.JPanel {

    /**
     * Creates new form PanelFormSignUp
     */
    public PanelFormSignUp() {
        initComponents();
    }
    
    public void addEventSignUp(ActionListener event) {
        btnSignUp.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        separatorUsername = new javax.swing.JSeparator();
        inputUsername = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        separatorFirstName = new javax.swing.JSeparator();
        inputFirstName = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        separatorLastName = new javax.swing.JSeparator();
        inputLastName = new javax.swing.JTextField();
        labelCI = new javax.swing.JLabel();
        separatorCI = new javax.swing.JSeparator();
        inputCI = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        separatorPhone = new javax.swing.JSeparator();
        inputPhone = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        separatorPassword = new javax.swing.JSeparator();
        inputPassword = new javax.swing.JPasswordField();
        iconShowAndHidden = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 210, 210));

        title.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        title.setForeground(new java.awt.Color(60, 60, 60));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Bienvenido");

        labelUsername.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(60, 60, 60));
        labelUsername.setLabelFor(inputUsername);
        labelUsername.setText("Usuario:");

        separatorUsername.setForeground(new java.awt.Color(41, 117, 185));

        inputUsername.setBackground(new java.awt.Color(180, 180, 180));
        inputUsername.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(55, 55, 55));
        inputUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputUsername.setName("Usuario"); // NOI18N

        labelFirstName.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelFirstName.setForeground(new java.awt.Color(60, 60, 60));
        labelFirstName.setLabelFor(inputFirstName);
        labelFirstName.setText("Nombre:");

        separatorFirstName.setForeground(new java.awt.Color(41, 117, 185));

        inputFirstName.setBackground(new java.awt.Color(180, 180, 180));
        inputFirstName.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputFirstName.setForeground(new java.awt.Color(55, 55, 55));
        inputFirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputFirstName.setName("Usuario"); // NOI18N

        labelLastName.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelLastName.setForeground(new java.awt.Color(60, 60, 60));
        labelLastName.setLabelFor(inputLastName);
        labelLastName.setText("Apellido:");

        separatorLastName.setForeground(new java.awt.Color(41, 117, 185));

        inputLastName.setBackground(new java.awt.Color(180, 180, 180));
        inputLastName.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputLastName.setForeground(new java.awt.Color(55, 55, 55));
        inputLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputLastName.setName("Usuario"); // NOI18N

        labelCI.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelCI.setForeground(new java.awt.Color(60, 60, 60));
        labelCI.setLabelFor(inputLastName);
        labelCI.setText("Cedula:");

        separatorCI.setForeground(new java.awt.Color(41, 117, 185));

        inputCI.setBackground(new java.awt.Color(180, 180, 180));
        inputCI.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputCI.setForeground(new java.awt.Color(55, 55, 55));
        inputCI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputCI.setName("Usuario"); // NOI18N

        labelPhone.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelPhone.setForeground(new java.awt.Color(60, 60, 60));
        labelPhone.setLabelFor(inputLastName);
        labelPhone.setText("Telefono:");

        separatorPhone.setForeground(new java.awt.Color(41, 117, 185));

        inputPhone.setBackground(new java.awt.Color(180, 180, 180));
        inputPhone.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputPhone.setForeground(new java.awt.Color(55, 55, 55));
        inputPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputPhone.setName("Usuario"); // NOI18N

        labelPassword.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(60, 60, 60));
        labelPassword.setLabelFor(inputLastName);
        labelPassword.setText("Contraseña:");

        separatorPassword.setForeground(new java.awt.Color(41, 117, 185));

        inputPassword.setBackground(new java.awt.Color(180, 180, 180));
        inputPassword.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));

        iconShowAndHidden.setBackground(new java.awt.Color(180, 180, 180));
        iconShowAndHidden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconShowAndHidden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        iconShowAndHidden.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        iconShowAndHidden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconShowAndHidden.setOpaque(true);

        btnSignUp.setBackground(new java.awt.Color(45, 155, 240));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(250, 250, 250));
        btnSignUp.setText("Registrarse");
        btnSignUp.setBorder(null);
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.setPreferredSize(new java.awt.Dimension(92, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputPassword)
                        .addGap(0, 0, 0)
                        .addComponent(iconShowAndHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(190, 190, 190))
                    .addComponent(inputUsername)
                    .addComponent(separatorUsername)
                    .addComponent(separatorFirstName)
                    .addComponent(inputFirstName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorLastName)
                    .addComponent(inputLastName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorCI)
                    .addComponent(inputCI)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorPhone)
                    .addComponent(inputPhone)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorPassword))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorCI, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCI, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconShowAndHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel iconShowAndHidden;
    private javax.swing.JTextField inputCI;
    private javax.swing.JTextField inputFirstName;
    private javax.swing.JTextField inputLastName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel labelCI;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JSeparator separatorCI;
    private javax.swing.JSeparator separatorFirstName;
    private javax.swing.JSeparator separatorLastName;
    private javax.swing.JSeparator separatorPassword;
    private javax.swing.JSeparator separatorPhone;
    private javax.swing.JSeparator separatorUsername;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
