package com.component;

import com.util.TableActionEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Cristian
 */
public class PanelActionTable extends javax.swing.JPanel {

    /**
     * Creates new form PanelActionTable
     *  @param onlyBtn: parametro que indica si solo va estar visible el btnDelete o todos los demas btn
     */
    public PanelActionTable() {
        initComponents();
    }
    
    public void onlyRemoveBtn(boolean onlyBtn) {
        btnActionEdit.setVisible(!onlyBtn);
    }
    
    public void initEvent(TableActionEvent event, int row) {
        btnActionEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
            }
        });
        btnActionRemove.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onRemove(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActionRemove = new com.component.complement.ActionButton();
        btnActionEdit = new com.component.complement.ActionButton();

        btnActionRemove.setBackground(new java.awt.Color(234, 78, 76));
        btnActionRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        btnActionRemove.setToolTipText("Remove");
        btnActionRemove.setBorder(null);
        btnActionRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnActionEdit.setBackground(new java.awt.Color(117, 231, 104));
        btnActionEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-icon.png"))); // NOI18N
        btnActionEdit.setToolTipText("Edit");
        btnActionEdit.setBorder(null);
        btnActionEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnActionRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActionRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActionEdit;
    private javax.swing.JButton btnActionRemove;
    // End of variables declaration//GEN-END:variables
}
