package com.component;

import com.event.ItemEvent;
import com.model.Product;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Cristian
 */
public class PanelSearch extends javax.swing.JPanel {

    private ItemEvent itemEvent;
    
    /**
     * Creates new form PanelSearch
     */
    public PanelSearch() {
        initComponents();
        searchContent.setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
    }
    
    public void addItemEvent(ItemEvent itemEvent) {
        this.itemEvent = itemEvent;
    }
    
    public void setListProductSearch(List<Object[]> listProductAndSelected) {
        searchContent.removeAll();
        
        for(Object[] data: listProductAndSelected) {
            SearchItem item = new SearchItem((Product) data[0], (boolean) data[1]);
            
            item.addEvent(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    itemEvent.onClick((Product) data[0]);
                }
            });
            
            searchContent.add(item, "wrap");
        }
        
        int count = getItemSize();
        
        if(count <= 5) {
            setPreferredSize(new Dimension(getPreferredSize().width, count * 36));
        } else setPreferredSize(new Dimension(getPreferredSize().width, 200));
        
        searchContent.setPreferredSize(new Dimension(searchContent.getPreferredSize().width, count * 36 ));
        
        repaint();
        revalidate();
    }
    
    public int getItemSize() {
        return searchContent.getComponentCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new com.component.complement.ScrollPaneWin11();
        searchContent = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(32767, 200));

        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setMinimumSize(new java.awt.Dimension(100, 40));

        searchContent.setMinimumSize(new java.awt.Dimension(100, 40));
        searchContent.setPreferredSize(new java.awt.Dimension(334, 198));

        javax.swing.GroupLayout searchContentLayout = new javax.swing.GroupLayout(searchContent);
        searchContent.setLayout(searchContentLayout);
        searchContentLayout.setHorizontalGroup(
            searchContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        searchContentLayout.setVerticalGroup(
            searchContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        scroll.setViewportView(searchContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel searchContent;
    // End of variables declaration//GEN-END:variables
}
