package com.component;

import com.model.Client;
import com.model.Sale;
import com.model.SaleInvoice;
import com.service.ClientService;
import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class PanelInvoice extends javax.swing.JPanel {

    private Client client;
    private SaleInvoice saleInvoice;
    private List<Sale> sales;
    
    /**
     * Creates new form PanelInvoice
     */
    public PanelInvoice(Object[] saleInvoice, List<Sale> sales) {
        initComponents();
        this.saleInvoice = (SaleInvoice) saleInvoice[0];
        this.client = (Client) saleInvoice[2];
        this.sales = sales;
    }
    
    public void setValues() {
        idInvoice.setText("N -" + saleInvoice.getId());
        fullName.setText(client.getFullName());
        phone.setText(client.getPhone());
        rif.setText(client.getRif());
        date.setText(saleInvoice.getCreateAt().toLocalDateTime().format(DateTimeFormatter.ofPattern("d/M/yyyy")));
        subTotal.setText(saleInvoice.getSubTotal().toPlainString());
        tax.setText(saleInvoice.getTax().toPlainString());
        total.setText(saleInvoice.getTotal().toPlainString());
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        for(Sale sale: sales)
            model.addRow(new Object[]{sale.getProductId(), sale.getQuantity(), "Nombre de ejemplo",
                                        sale.getAmount(), sale.getAmount().divide(new BigDecimal(sale.getQuantity())).setScale(2, RoundingMode.HALF_UP)});
        
//        scrollTable.setPreferredSize(new Dimension(scrollTable.getPreferredSize().width, model.getRowCount() * 32));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        idInvoice = new javax.swing.JLabel();
        labelFullName = new javax.swing.JLabel();
        fullName = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        labelRif = new javax.swing.JLabel();
        rif = new javax.swing.JLabel();
        scrollTable = new com.component.complement.ScrollPaneWin11();
        table = new com.component.complement.TableCustom(new Color(41,117,185), new Color(162,175,186), new Color(200,218, 234), new Color(160,160,175));
        labelSubTotal = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();
        labelTax = new javax.swing.JLabel();
        tax = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 210, 210));

        title.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(41, 117, 185));
        title.setText("Factura");

        labelDate.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelDate.setForeground(new java.awt.Color(41, 117, 185));
        labelDate.setText("Fecha:");

        date.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        date.setForeground(new java.awt.Color(50, 50, 50));
        date.setText("01/02/2001");

        idInvoice.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        idInvoice.setForeground(new java.awt.Color(234, 78, 76));
        idInvoice.setText("N {idInvoice}");

        labelFullName.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelFullName.setForeground(new java.awt.Color(41, 117, 185));
        labelFullName.setText("Nombre o Razón Social:");

        fullName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fullName.setForeground(new java.awt.Color(50, 50, 50));
        fullName.setText("{fullName}");

        labelPhone.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelPhone.setForeground(new java.awt.Color(41, 117, 185));
        labelPhone.setText("Telefono:");

        phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(50, 50, 50));
        phone.setText("{0412-1128262}");

        labelRif.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelRif.setForeground(new java.awt.Color(41, 117, 185));
        labelRif.setText("Rif:");

        rif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rif.setForeground(new java.awt.Color(50, 50, 50));
        rif.setText("V-30001270");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cantidad", "Nombre", "Precio Unitario", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(31);
        scrollTable.setViewportView(table);

        labelSubTotal.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelSubTotal.setForeground(new java.awt.Color(41, 117, 185));
        labelSubTotal.setText("Sub-Total:");

        subTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        subTotal.setForeground(new java.awt.Color(50, 50, 50));
        subTotal.setText("{subTotal}");

        labelTax.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelTax.setForeground(new java.awt.Color(41, 117, 185));
        labelTax.setText("IVA 16%:");

        tax.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tax.setForeground(new java.awt.Color(50, 50, 50));
        tax.setText("{Impuestos}");

        labelTotal.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(41, 117, 185));
        labelTotal.setText("Total:");

        total.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        total.setForeground(new java.awt.Color(50, 50, 50));
        total.setText("{Total}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFullName)
                            .addComponent(idInvoice)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPhone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelRif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rif))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(fullName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tax)))
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDate)
                        .addComponent(date)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhone)
                    .addComponent(phone)
                    .addComponent(labelRif)
                    .addComponent(rif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubTotal)
                    .addComponent(subTotal)
                    .addComponent(labelTax)
                    .addComponent(tax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(total))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel fullName;
    private javax.swing.JLabel idInvoice;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelFullName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelRif;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelTax;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel rif;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JLabel subTotal;
    private javax.swing.JTable table;
    private javax.swing.JLabel tax;
    private javax.swing.JLabel title;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
