package com.component;

import java.awt.event.ActionListener;

/**
 *
 * @author Cristian
 */
public class PanelFormForgot extends javax.swing.JPanel {

    /**
     * Creates new form PanelFormForgot
     */
    public PanelFormForgot() {
        initComponents();
    }
    
    public void addEventBackLogin(ActionListener event) {
        btnBack.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        labelUsername = new javax.swing.JLabel();
        separatorUsername = new javax.swing.JSeparator();
        inputUsername = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        separatorFirstName = new javax.swing.JSeparator();
        inputFirstName = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        separatorLastName = new javax.swing.JSeparator();
        inputLastName = new javax.swing.JTextField();
        labelCI = new javax.swing.JLabel();
        separatorCI = new javax.swing.JSeparator();
        inputCI = new javax.swing.JTextField();
        btnInit = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 210, 210));

        btnBack.setBackground(new java.awt.Color(210, 210, 210));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBack.setOpaque(true);

        labelUsername.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(60, 60, 60));
        labelUsername.setText("Usuario:");

        separatorUsername.setForeground(new java.awt.Color(41, 117, 185));

        inputUsername.setBackground(new java.awt.Color(180, 180, 180));
        inputUsername.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(55, 55, 55));
        inputUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputUsername.setName("Usuario"); // NOI18N

        labelFirstName.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelFirstName.setForeground(new java.awt.Color(60, 60, 60));
        labelFirstName.setText("Nombre:");

        separatorFirstName.setForeground(new java.awt.Color(41, 117, 185));

        inputFirstName.setBackground(new java.awt.Color(180, 180, 180));
        inputFirstName.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputFirstName.setForeground(new java.awt.Color(55, 55, 55));
        inputFirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputFirstName.setName("Usuario"); // NOI18N

        labelLastName.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelLastName.setForeground(new java.awt.Color(60, 60, 60));
        labelLastName.setText("Apellido:");

        separatorLastName.setForeground(new java.awt.Color(41, 117, 185));

        inputLastName.setBackground(new java.awt.Color(180, 180, 180));
        inputLastName.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputLastName.setForeground(new java.awt.Color(55, 55, 55));
        inputLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputLastName.setName("Usuario"); // NOI18N

        labelCI.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelCI.setForeground(new java.awt.Color(60, 60, 60));
        labelCI.setText("Cedula:");

        separatorCI.setForeground(new java.awt.Color(41, 117, 185));

        inputCI.setBackground(new java.awt.Color(180, 180, 180));
        inputCI.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inputCI.setForeground(new java.awt.Color(55, 55, 55));
        inputCI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(41, 117, 185)));
        inputCI.setName("Usuario"); // NOI18N

        btnInit.setBackground(new java.awt.Color(45, 155, 240));
        btnInit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInit.setForeground(new java.awt.Color(250, 250, 250));
        btnInit.setText("Ingresar");
        btnInit.setBorder(null);
        btnInit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInit.setPreferredSize(new java.awt.Dimension(92, 30));
        btnInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(190, 190, 190))
                    .addComponent(inputUsername)
                    .addComponent(separatorUsername)
                    .addComponent(separatorFirstName)
                    .addComponent(inputFirstName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorLastName)
                    .addComponent(inputLastName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162))
                    .addComponent(separatorCI)
                    .addComponent(inputCI))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorCI, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCI, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInit;
    private javax.swing.JTextField inputCI;
    private javax.swing.JTextField inputFirstName;
    private javax.swing.JTextField inputLastName;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel labelCI;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JSeparator separatorCI;
    private javax.swing.JSeparator separatorFirstName;
    private javax.swing.JSeparator separatorLastName;
    private javax.swing.JSeparator separatorUsername;
    // End of variables declaration//GEN-END:variables
}
