package com.component;

import com.model.Product;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Cristian
 */
public class SearchItem extends javax.swing.JPanel {

    public final Color normal = new Color(230,230,230), hover = new Color(210,210,210);
    private ActionListener eventClick;
    
    /**
     * Creates new form SearchItem
     */
    public SearchItem(Product product, boolean selected) {
        initComponents();
        textSearch.setText(product.getTitle());
        if(product.getAvailability() == 0) 
            iconStock.setIcon(new ImageIcon(getClass().getResource("/low-stock.png")));
        if(selected)
            iconSearch.setIcon(new ImageIcon(getClass().getResource("/history.png")));
    }

    public void addEvent(ActionListener eventClick) { 
        this.eventClick = eventClick;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconSearch = new javax.swing.JLabel();
        textSearch = new javax.swing.JLabel();
        iconStock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 230, 230));
        setPreferredSize(new java.awt.Dimension(334, 36));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        iconSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        iconSearch.setMinimumSize(new java.awt.Dimension(37, 24));
        iconSearch.setPreferredSize(new java.awt.Dimension(37, 24));

        textSearch.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textSearch.setForeground(new java.awt.Color(60, 60, 60));
        textSearch.setText("{Texto de Busqueda}");

        iconStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        iconStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/got-stock.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(textSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(iconStock, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(textSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(hover);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(normal);
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        eventClick.actionPerformed(null);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconSearch;
    private javax.swing.JLabel iconStock;
    private javax.swing.JLabel textSearch;
    // End of variables declaration//GEN-END:variables
}
