package com.component;

import com.event.ItemEvent;
import com.model.User;
import com.model.UserInfo;

/**
 *
 * @author Cristian
 */
public class UserItem extends javax.swing.JPanel {
    
    private User user;
    private UserInfo userInfo;
    private ItemEvent itemEvent;
    
    /**
     * Creates new form UserItem
     */
    public UserItem(User user, UserInfo userInfo, ItemEvent itemEvent) {
        initComponents();
        this.user = user;
        this.userInfo = userInfo;
        this.itemEvent = itemEvent; 
        setValues();
    }
    
    //* Insertar los datos del usuario en la interfaz visual
    private void setValues() {
        labelUsername.setText("Nombre de Usuario: " + user.getUsername());
        labelFirstName.setText("Nombre: " + userInfo.getFirstName());
        labelLastName.setText("Apellido: " + userInfo.getLastName());
        labelPhone.setText("Telefono: " + userInfo.getPhone());
        labelCI.setText("CI: " + userInfo.getCi());
        labelRole.setText("Role: " + user.getPosition());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsername = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelCI = new javax.swing.JLabel();
        labelRole = new javax.swing.JLabel();
        btnEdit = new com.component.complement.ActionButton(40);
        btnRemove = new com.component.complement.ActionButton(40);

        setBackground(new java.awt.Color(225, 225, 225));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(148, 148, 148)));
        setMaximumSize(new java.awt.Dimension(450, 240));
        setPreferredSize(new java.awt.Dimension(428, 232));

        labelUsername.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(30, 30, 30));
        labelUsername.setText("Nombre de Usuario: {username}");

        labelFirstName.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelFirstName.setForeground(new java.awt.Color(30, 30, 30));
        labelFirstName.setText("Nombre: {name}");

        labelLastName.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelLastName.setForeground(new java.awt.Color(30, 30, 30));
        labelLastName.setText("Apellido: {lastName}");

        labelPhone.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelPhone.setForeground(new java.awt.Color(30, 30, 30));
        labelPhone.setText("Telefono: {Phone}");

        labelCI.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelCI.setForeground(new java.awt.Color(30, 30, 30));
        labelCI.setText("CI: {ci}");

        labelRole.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelRole.setForeground(new java.awt.Color(30, 30, 30));
        labelRole.setText("Role: {role}");

        btnEdit.setBackground(new java.awt.Color(190, 190, 190));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-icon.png"))); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(190, 190, 190));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash_logo.png"))); // NOI18N
        btnRemove.setPreferredSize(new java.awt.Dimension(40, 40));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCI)
                            .addComponent(labelPhone)
                            .addComponent(labelFirstName)
                            .addComponent(labelUsername)
                            .addComponent(labelLastName))
                        .addContainerGap(136, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCI)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRole)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        itemEvent.onRemove(user.getId());
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        itemEvent.onEdit(user, userInfo);
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel labelCI;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
