package com.demo;

import com.DB.Database;
import com.model.Sale;
import com.model.User;
import com.service.UserService;
import com.view.Background;
import com.view.Invoice;
import com.view.Login;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Cristian
 * Clase principal que donde se ejecuta la ventana del programa
 * y confirma si los demas modulos/ paquetes estan listos
 */
public class Demo extends javax.swing.JFrame {
    
    /** 
     * Objetos que ayudan la integracion de interfaces visuales a la ventana y datos para el uso general de la aplicacion
     * 
     * login: panel que ayuda a la integracion como el formulario del login, signup y forgot
     * background: panel que ayuda la integracion de componentes como SalePanel, Header, MenuBar, etc.
     * user: objeto que almacena los datos del usario al iniciar sesion
     */
    
    public static Login login;
    public static Invoice invoice;
    public static Background background;
    public static User user;
    
    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
        try {
            login = new Login();
            
            if(new UserService().getCountUsers() == 0) {
                login.initFormSignUp();
            } else login.initFormLogin();
            
            setContentPane(login);
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Base de datos no encontrada","Error",JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        
    }
    
    //* Cambia la vista de la ventana al Background
    public void goToBackgroundView() {
        background = new Background();
        setView(background);
    }
    
    //* Cambia la vista de la ventana al Login
    public void goToLoginView() {
        login = new Login();
        login.initFormLogin();
        setView(login);
    }
    
    public void goToInvoiceView(Object[] saleInvoice, List<Sale> sales) {
        invoice = new Invoice(saleInvoice, sales);
        setView(invoice);
    }
    
    //* Cambia la vista de la ventana por cualquier panel que se le pase por paramatro
    private void setView(JPanel view) {
        setContentPane(view);
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1032, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>
        
        //* Si no encuentra los controladeres de la base de datos, cierra el programa
        if(!Database.verifyController()) {
            JOptionPane.showMessageDialog(null,"Conector de Base de Datos, No encontrado","Alerta",JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
