package com.view;

import com.component.PanelInvoice;
import com.model.Sale;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Cristian
 */
public class Invoice extends javax.swing.JPanel {

    public PanelInvoice panelInvoice;
    
    /**
     * Creates new form Invoice
     */
    public Invoice(Object[] saleInvoice, List<Sale> sales) {
        initComponents();
        
        panelInvoice = new PanelInvoice(saleInvoice, sales);
        panelInvoice.setValues();
        
        setPanelForm(panelInvoice);
        
    }
    
    //* Funcion que se encarga de cambiar los formularios dependiendo del que se le pase por parametro
    private void setPanelForm(JPanel content) {
        content.setSize(content.getPreferredSize());
        invoice.removeAll();
        invoice.add(content);
        invoice.setPreferredSize(content.getPreferredSize());
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new com.component.complement.ScrollPaneWin11();
        content = new javax.swing.JPanel();
        invoice = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        content.setBackground(new java.awt.Color(41, 117, 185));

        invoice.setBackground(new java.awt.Color(210, 210, 210));

        javax.swing.GroupLayout invoiceLayout = new javax.swing.GroupLayout(invoice);
        invoice.setLayout(invoiceLayout);
        invoiceLayout.setHorizontalGroup(
            invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        invoiceLayout.setVerticalGroup(
            invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        scroll.setViewportView(content);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JPanel invoice;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
