package com.view;

import com.component.PanelFormForgot;
import com.component.PanelFormLogin;
import com.component.PanelFormSignUp;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author Cristian
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public Login() {
        initComponents();
    }
    
    public void initFormSignUp() {
        PanelFormSignUp panelFormSignUp = new PanelFormSignUp();
        setPanelForm(panelFormSignUp);
    }
    
    public void initFormLogin() {
        PanelFormLogin panelFormLogin = new PanelFormLogin();
        setPanelForm(panelFormLogin);
        panelFormLogin.addEventForgotPassword(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                initFormForgot();
            }
        });
    }
    
    public void initFormForgot() {
        PanelFormForgot panelFormForgot = new PanelFormForgot();
        setPanelForm(panelFormForgot);
        panelFormForgot.addEventBackLogin(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                initFormLogin();
            }
        });
    }
    
    private void setPanelForm(JPanel content) {
        content.setSize(content.getPreferredSize());
        panelForm.removeAll();
        panelForm.add(content);
        panelForm.setPreferredSize(content.getPreferredSize());
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForm = new javax.swing.JPanel();

        setBackground(new java.awt.Color(41, 117, 185));
        setMinimumSize(new java.awt.Dimension(1032, 680));

        panelForm.setBackground(new java.awt.Color(210, 210, 210));
        panelForm.setPreferredSize(new java.awt.Dimension(300, 350));

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(490, Short.MAX_VALUE)
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 185, Short.MAX_VALUE)
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelForm;
    // End of variables declaration//GEN-END:variables
}
